Further fixes around link creation
* build.gradle
** Some test failures threw an exception in trying to explain the test failure
because mockito-all is incompatible with junit 4.11 and above.  Solution is to
switch to mockito-core.  See
https://tedvinke.wordpress.com/2013/12/17/mixing-junit-hamcrest-and-mockito-explaining-nosuchmethoderror/

* custom-gradle-core-plugin\src\main\kotlin\holygradle\io\Junction.kt
** In rebuild, the original Groovy was reassigning to the argument "target",
which I missed in the Kotlin conversion (which doesn't allow that).
** I mis-interpreted Byte.SIZE as 1, when it should be 8, which caused all
attempts to create junctions to fail.

* custom-gradle-core-plugin\src\test\groovy\holygradle\io\LinkTestBase.groovy
** Clean out non-empty directory during test setup.