In passing, fix an odd mis-feature I found.
If you write a packedDependencies block which declares different dependencies
at the same path ... what it in fact does is replace the module dependency info
in the existing PackedDependenciesHandler object, meaning that the symlink
creation phase will fail for one of the two, with the following exception.

--------
java.lang.RuntimeException: Module 'holygradle.test:another-lib:1.0' has no parent module.
	at holygradle.unpacking.UnpackModuleVersion.<init>(UnpackModuleVersion.groovy:47)
	at holygradle.unpacking.UnpackModuleVersion.<init>(UnpackModuleVersion.groovy:27)
	at holygradle.unpacking.PackedDependenciesStateHandler$_collectUnpackModules_closure2.doCall(PackedDependenciesStateHandler.groovy:194)
	at holygradle.dependencies.ResolvedDependenciesVisitor$_doTraverseResolvedDependencies_closure1.doCall(ResolvedDependenciesVisitor.groovy:90)
	at holygradle.dependencies.ResolvedDependenciesVisitor.doTraverseResolvedDependencies(ResolvedDependenciesVisitor.groovy:82)
	at holygradle.dependencies.ResolvedDependenciesVisitor.traverseResolvedDependencies(ResolvedDependenciesVisitor.groovy:126)
	at holygradle.dependencies.ResolvedDependenciesVisitor$traverseResolvedDependencies.call(Unknown Source)
	at holygradle.dependencies.ResolvedDependenciesVisitor$traverseResolvedDependencies.call(Unknown Source)
	at holygradle.unpacking.PackedDependenciesStateHandler.collectUnpackModules(PackedDependenciesStateHandler.groovy:92)
	at holygradle.unpacking.PackedDependenciesStateHandler.this$2$collectUnpackModules(PackedDependenciesStateHandler.groovy)
	at holygradle.unpacking.PackedDependenciesStateHandler$_initializeAllUnpackModules_closure3.doCall(PackedDependenciesStateHandler.groovy:232)
	at holygradle.unpacking.PackedDependenciesStateHandler.initializeAllUnpackModules(PackedDependenciesStateHandler.groovy:228)
	at holygradle.unpacking.PackedDependenciesStateHandler.getAllUnpackModules(PackedDependenciesStateHandler.groovy:216)
	at holygradle.unpacking.SpeedyUnpackManyTask$_addUnpackModuleVersions_closure2.doCall(SpeedyUnpackManyTask.groovy:41)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:58)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:133)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:113)
	at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:425)
	at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:58)
	at org.gradle.util.Configurable$configure.call(Unknown Source)
	at holygradle.IntrepidPlugin$_apply_closure16_closure29.doCall(IntrepidPlugin.groovy:243)
	at holygradle.IntrepidPlugin$_apply_closure16_closure29.doCall(IntrepidPlugin.groovy)
	at holygradle.custom_gradle.util.ProfilingHelper.timing(ProfilingHelper.groovy:49)
	at holygradle.IntrepidPlugin$_apply_closure16.doCall(IntrepidPlugin.groovy:242)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:81)
-------

I fixed this by just not allowing it to be overwritten.  In doing this, I
refactored three bits of internal state into one (to make the "initialised
already?" check simpler).

I didn't bother writing a test for this, because nobody ever hit it but me, and
there's now an explicit exception thrown in the code, which you'd have to remove
to break it again.